### ISSUE TITLE
example doesn't run

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#11]
After running `yarn install` then `yarn start`

```
ERROR in ./app.js
Module build failed: ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "/Users/booker/Code/revalidation/.babelrc" at 0, attempted to resolve relative to "/Users/booker/Code/revalidation"
    at /Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/booker/Code/revalidation/example/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (/Users/booker/Code/revalidation/example/node_modules/babel-loader/lib/index.js:163:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js
```

**Comment by busypeoples** [comment]
Can't replicate the error.
```
cd example
yarn install
npm start // or yarn start
```

Should actually run. Can you remove node_modules and try again?

**Comment by bookercodes** [comment]
Yeah, of course! 

Unfortunately, I get the same error:

```
~/Code/revalidation master
► cd example

~/Code/revalidation/example master
► rm -rf node_modules

~/Code/revalidation/example master
► yarn install
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 8.09s.

~/Code/revalidation/example master 8s
► yarn start
yarn start v0.24.5
$ webpack-dev-server
Project is running at http://localhost:8080/
webpack output is served from /
Hash: 9151a33f9de3115ff78b
Version: webpack 2.6.1
Time: 1143ms
        Asset    Size  Chunks                    Chunk Names
    bundle.js  317 kB       0  [emitted]  [big]  app
bundle.js.map  375 kB       0  [emitted]         app
chunk    {0} bundle.js, bundle.js.map (app) 303 kB [entry] [rendered]
   [35] ./app.js 1.46 kB {0} [built] [failed] [1 error]
   [36] (webpack)-dev-server/client?http://localhost:8080 5.68 kB {0} [built]
   [37] ./~/ansi-html/index.js 4.26 kB {0} [built]
   [38] ./~/ansi-regex/index.js 135 bytes {0} [built]
   [40] ./~/events/events.js 8.33 kB {0} [built]
   [41] ./~/html-entities/index.js 231 bytes {0} [built]
   [48] ./~/querystring-es3/index.js 127 bytes {0} [built]
   [51] ./~/sockjs-client/lib/entry.js 244 bytes {0} [built]
   [77] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [78] ./~/url/url.js 23.3 kB {0} [built]
   [79] ./~/url/util.js 314 bytes {0} [built]
   [80] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [81] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
   [83] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [84] multi (webpack)-dev-server/client?http://localhost:8080 ./app.js 40 bytes {0} [built]
     + 70 hidden modules

ERROR in ./app.js
Module build failed: ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "/Users/booker/Code/revalidation/.babelrc" at 0, attempted to resolve relative to "/Users/booker/Code/revalidation"
    at /Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/booker/Code/revalidation/example/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/booker/Code/revalidation/example/node_modules/babel-loader/lib/index.js:48:20)
    at Object.module.exports (/Users/booker/Code/revalidation/example/node_modules/babel-loader/lib/index.js:163:20)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.js
webpack: Failed to compile.

```

Seems like `package.json` is missing a dependency (do you have it installed globally?)

Sorry, I haven't really tried to debug this, I ran `yarn add babel-plugin-transform-flow-strip-types --dev` but the problem continues. Will look into it tomorrow

**Comment by busypeoples** [comment]
The `babel-plugin-transform-flow-strip-types` should be a dev dependency in `package.json`. I'll retry tomorrow and let you know!

**Comment by busypeoples** [comment]
The problem is that, only doing yarn install inside the example folder without doing a yarn install inside project root will cause this error.  Added a babel config to the example folder. This should solve the problem.

**Comment by bookercodes** [comment]
Awesome, nice one @busypeoples !!

**Comment by busypeoples** [comment]
We can close this issue, in case the example works now.

**Comment by bookercodes** [comment]
Great, it works now, thanks!
